DROP TABLE IF EXISTS Sucursal_Trabajador;
DROP TABLE IF EXISTS Cita_Lavado;
DROP TABLE IF EXISTS Trabajador_Cita;
DROP TABLE IF EXISTS Proveedor_Producto;
DROP TABLE IF EXISTS Direccion;
DROP TABLE IF EXISTS Trabajador;
DROP TABLE IF EXISTS Telefono;
DROP TABLE IF EXISTS Lavado;
DROP TABLE IF EXISTS Producto;
DROP TABLE IF EXISTS Proveedor;
DROP TABLE IF EXISTS Sucursal;
DROP TABLE IF EXISTS Cita;
DROP TABLE IF EXISTS Cliente;

